name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: AnarchI-Technologies-MAIN/.github/.github/workflows/reusable-python.yml@6cb93b6a89db636c59f0094da23d9deec4732e13
    with:
      python-version: "3.12"
      extras: ""
      test-kind: unittest
